# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java-version: [7, 8, 11, 14]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Install ffmpeg on Ubuntu
        run: sudo apt-get update && sudo apt-get install -y ffmpeg && ffmpeg -version
        if:  startsWith(matrix.os, 'ubuntu')

      - name: Install ffmpeg on MacOS
        run: brew install ffmpeg && ls -lhtr /usr/local/opt/ffmpeg/ && ffmpeg -version
        if:  startsWith(matrix.os, 'macos')

      - name: Install ffmpeg on Windows
        run: choco install ffmpeg && ffmpeg -version
        if:  startsWith(matrix.os, 'windows')

      - name: Build on Ubuntu
        run: mvn -B package --file pom.xml -DFFMPEG_BIN=/usr/bin
        if: startsWith(matrix.os, 'ubuntu')

      - name: Build on MacOS
        run: mvn -B package --file pom.xml -DFFMPEG_BIN=/usr/local/opt/ffmpeg/bin
        if: startsWith(matrix.os, 'macos')

      - name: Build on Windows
        run: mvn -B package --file pom.xml "-DFFMPEG_BIN=C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\bin"
        if: startsWith(matrix.os, 'windows')
